# Generated by Django 5.2 on 2025-04-16 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meteor_app', '0002_alter_astronomyevent_table_forumpost_forumcomment_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='astronomyevent',
            table='login',
        ),
        migrations.AlterModelTable(
            name='forumcomment',
            table='forum_comment_table',
        ),
        migrations.AlterModelTable(
            name='forumfavorite',
            table='forum_favorite_table',
        ),
        migrations.AlterModelTable(
            name='forumpost',
            table='forum_post_table',
        ),
    ]
