# Generated by Django 5.0.3 on 2025-04-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteor_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AstronomyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
